# Name of the workflow that will appear in the GitHub Actions tab
name: Cypress Tests (Push & PR)

# Define when the workflow should be triggered
on:
  push:                 # Trigger the workflow on every push to the main branch
    branches: [ main ]
  pull_request:         # Also trigger the workflow on pull requests targeting main
    branches: [ main ]

# Define the job that will run the Cypress tests
jobs:
  cypress-run:
    runs-on: ubuntu-latest   # Use the latest Ubuntu Linux environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment with version 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install all project dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests using the correct script (with video/screenshot support)
      # This script runs all test modules sequentially with mochawesome reports
      - name: Run Cypress tests
        run: npm run report:all:split

      # Step 5: Upload screenshots if any test fails (for debugging)
      - name: Upload screenshots
        if: failure()   # Only runs if the previous step failed
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Step 6: Upload Cypress videos (always, even if tests pass)
      - name: Upload videos
        if: always()    # Runs regardless of success or failure
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos